CREATE TABLE IF NOT EXISTS `User`(
    id INT AUTO_INCREMENT PRIMARY KEY,
    userId VARCHAR(255) NOT NULL UNIQUE,
    nickName VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS `UserInfo`(
    userId INT PRIMARY KEY,
    userName VARCHAR(255),
    email VARCHAR(255) UNIQUE DEFAULT 'email',
    profileImageUrl VARCHAR(255) DEFAULT 'image',
    createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (userId) REFERENCES USER_DB.`User`(id) ON DELETE CASCADE ON UPDATE CASCADE
);