services:
  api_server:
    image: hanwj75/myserver1:1
    depends_on:
      - mysql
    environment:
      - PORT=3333
      - HOST=0.0.0.0
      - DB1_HOST=mysql
      - DB1_PORT=3306
      - DB1_USER=root
      - DB1_PASSWORD=1234
      - DB1_NAME=USER_DB
      - DB2_HOST=mysql
      - DB2_PORT=3306
      - DB2_USER=root
      - DB2_PASSWORD=1234
      - DB2_NAME=POST_DB
      - JWT_KEY=JWT_SECRET_KEY
    ports:
      - "3333:3333"
    networks:
      - apinetwork
    restart: always # 오류 시 자동 재시작 추가
    command: ["sh", "-c", "yarn migrate && node src/app.js"]

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: USER_DB
      MYSQL_USER: account
      MYSQL_PASSWORD: 1234

    ports:
      - "5555:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - apinetwork

networks:
  apinetwork:

volumes:
  mysql-data:
